// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydufqigukfpaahuvbmgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdWZxaWd1a2ZwYWFodXZibWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjMyNjUsImV4cCI6MjA3MDAzOTI2NX0.F7memcj-wY08m_p_gowq7HkvmNMzUmU2HOWIXpCTBYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});